# Generated by Django 4.2.30 on 2026-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quizsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_logo',
            field=models.ImageField(blank=True, help_text='Upload brand/company logo for the certificate footer', null=True, upload_to='certificate_logos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='primary_signatory_name',
            field=models.CharField(default='Charles Bukolo', help_text='Name of the course creator/primary authority', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='primary_signatory_title',
            field=models.CharField(default='Empower Edge', help_text='Title/Organization of the primary signatory', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='primary_signature_image',
            field=models.ImageField(blank=True, help_text='Upload signature image line overlay', null=True, upload_to='certificate_signatures/'),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_signatory_name',
            field=models.CharField(default='Chitongwa Banda', help_text='Collaborator name (e.g., BeRelevant Afrika)', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_signatory_title',
            field=models.CharField(default='BeRelevant Afrika', help_text='Title/Organization of the secondary signatory', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_signature_image',
            field=models.ImageField(blank=True, help_text='Upload partner authority signature overlay', null=True, upload_to='certificate_signatures/'),
        ),
    ]
