# Generated by Django 4.2.28 on 2026-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDUCATOR', 'Educator'), ('LEARNER', 'Learner')], default='LEARNER', max_length=10),
        ),
    ]
